ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.generated.webmenu.ApplicationGeneratedKt.generatedModule ]
    }
}

storage {
    jdbcUrl = ${JDBC_DATABASE_URL}
    dbUser = ${JDBC_DATABASE_USERNAME}
    dbPassword = ${JDBC_DATABASE_PASSWORD}
}
